-- MySQL Script generated by MySQL Workbench
-- 11/26/19 10:36:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistemagerente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemagerente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemagerente` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sistemagerente` ;

-- -----------------------------------------------------
-- Table `sistemagerente`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`funcionarios` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NULL COMMENT '',
  `CPF` VARCHAR(11) NULL COMMENT '',
  `endereco` VARCHAR(200) NULL COMMENT '',
  `sexo` VARCHAR(20) NULL COMMENT '',
  `funcao` VARCHAR(45) NULL COMMENT '',
  `telefone` VARCHAR(11) NULL COMMENT '',
  `whatsapp` VARCHAR(11) NULL COMMENT '',
  `senha` VARCHAR(100) NULL COMMENT '',
  `email` VARCHAR(100) NULL COMMENT '',
  `status` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idFuncionario`)  COMMENT '',
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemagerente`.`caixas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`caixas` (
  `idCaixa` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `idFuncionario` INT NOT NULL COMMENT '',
  `saldoInicial` DECIMAL(10,2) NULL COMMENT '',
  `status` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCaixa`)  COMMENT '',
  INDEX `fk_caixa_funcionario_idx` (`idFuncionario` ASC)  COMMENT '',
  CONSTRAINT `fk_caixa_funcionario`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `sistemagerente`.`funcionarios` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemagerente`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `status` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCategoria`)  COMMENT '',
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemagerente`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  `idCategoria` INT NOT NULL COMMENT '',
  `foto` VARCHAR(45) NULL COMMENT '',
  `precoCusto` DECIMAL(10,2) NULL COMMENT '',
  `precoVenda` DECIMAL(10,2) NULL COMMENT '',
  `status` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idProduto`)  COMMENT '',
  INDEX `fk_produto_categoria1_idx` (`idCategoria` ASC)  COMMENT '',
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `sistemagerente`.`categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemagerente`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`mesas` (
  `idMesa` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idMesa`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistemagerente`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `data` DATETIME NULL COMMENT '',
  `idFuncionario` INT NOT NULL COMMENT '',
  `idMesa` INT NOT NULL COMMENT '',
  `observacao` VARCHAR(200) NULL COMMENT '',
  `qtdItens` INT NULL COMMENT '',
  `totalPedido` DECIMAL(10,2) NULL COMMENT '',
  `desconto` DECIMAL(10,2) NULL COMMENT '',
  `tipoRecebimento` INT NULL COMMENT '',
  `valorRecebido` DECIMAL(10,2) NULL COMMENT '',
  `situacao` VARCHAR(45) NOT NULL COMMENT '',
  `status` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPedido`)  COMMENT '',
  INDEX `fk_pedidos_funcionarios1_idx` (`idFuncionario` ASC)  COMMENT '',
  INDEX `fk_pedidos_mesas1_idx` (`idMesa` ASC)  COMMENT '',
  CONSTRAINT `fk_pedidos_funcionarios1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `sistemagerente`.`funcionarios` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_mesas1`
    FOREIGN KEY (`idMesa`)
    REFERENCES `sistemagerente`.`mesas` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemagerente`.`itensPedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`itensPedidos` (
  `idPedido` INT NOT NULL COMMENT '',
  `idProduto` INT NOT NULL COMMENT '',
  `quantidade` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPedido`, `idProduto`)  COMMENT '',
  INDEX `fk_pedidos_has_produtos_produtos1_idx` (`idProduto` ASC)  COMMENT '',
  INDEX `fk_pedidos_has_produtos_pedidos1_idx` (`idPedido` ASC)  COMMENT '',
  CONSTRAINT `fk_pedidos_has_produtos_pedidos1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `sistemagerente`.`pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_produtos_produtos1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `sistemagerente`.`produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `sistemagerente`.`caixas` (`nome`, `idFuncionario`, `saldoInicial`, `status`) VALUES ('CAIXA 01', '1', '100.00', '1');
INSERT INTO `sistemagerente`.`caixas` (`nome`, `idFuncionario`, `saldoInicial`, `status`) VALUES ('CAIXA 02', '2', '100.00', '1');

INSERT INTO `sistemagerente`.`categorias` (`nome`, `status`) VALUES ('REFRIGERANTE', '1');
INSERT INTO `sistemagerente`.`categorias` (`nome`, `status`) VALUES ('SANDUICHE', '1');

INSERT INTO `sistemagerente`.`funcionarios` (`nome`, `CPF`, `endereco`, `sexo`, `funcao`, `telefone`, `whatsapp`, `senha`, `email`, `status`) VALUES ('JONATAS', '55555', 'TESTE', 'Masculino', 'Administrador', '333323', '3232323', md5('123'), 'jonatas@gmail.com', '1');
INSERT INTO `sistemagerente`.`funcionarios` (`nome`, `CPF`, `endereco`, `sexo`, `funcao`, `telefone`, `whatsapp`, `senha`, `email`, `status`) VALUES ('TESTE', '123456', 'TESTE', 'Feminino', 'Cozinheiro', '323232323', '323232323', md5('123'), 'teste@gmail.com', '1');

INSERT INTO `sistemagerente`.`mesas` (`nome`) VALUES ('MESA 1');
INSERT INTO `sistemagerente`.`mesas` (`nome`) VALUES ('MESA 2');

INSERT INTO `sistemagerente`.`produtos` (`nome`, `idCategoria`, `foto`, `precoCusto`, `precoVenda`, `status`) VALUES ('COCA COLA', '1', 'cocacola.jpg', '2.00', '5.00', '1');
INSERT INTO `sistemagerente`.`produtos` (`nome`, `idCategoria`, `foto`, `precoCusto`, `precoVenda`, `status`) VALUES ('X SALADA', '2', 'x_salada.png', '6.00', '10.00', '1');





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
