-- MySQL Script generated by MySQL Workbench
-- qua 09 out 2019 19:46:43 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistemagerente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemagerente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemagerente` DEFAULT CHARACTER SET utf8 ;
USE `sistemagerente` ;

-- -----------------------------------------------------
-- Table `sistemagerente`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`funcionarios` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `CPF` VARCHAR(11) NULL,
  `endereco` VARCHAR(200) NULL,
  `funcao` INT NULL,
  `telefone` VARCHAR(11) NULL,
  `whatsapp` VARCHAR(11) NULL,
  `senha` VARCHAR(45) NULL,
  `e-mail` VARCHAR(100) NULL,
  PRIMARY KEY (`idFuncionario`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemagerente`.`caixas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`caixas` (
  `idCaixa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idCaixa`),
  INDEX `fk_caixa_funcionario_idx` (`idFuncionario` ASC),
  CONSTRAINT `fk_caixa_funcionario`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `sistemagerente`.`funcionarios` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemagerente`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`categorias` (
  `idCategoria` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemagerente`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `idCategoria` INT NOT NULL,
  `precoCusto` DECIMAL(10,2) NULL,
  `precoVenda` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_produto_categoria1_idx` (`idCategoria` ASC),
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `sistemagerente`.`categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemagerente`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`mesas` (
  `idMesa` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idMesa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistemagerente`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`pedidos` (
  `idPedido` INT NOT NULL,
  `data` VARCHAR(45) NULL,
  `idFuncionario` INT NOT NULL,
  `idMesa` INT NOT NULL,
  `observacao` VARCHAR(200) NULL,
  `qtdItens` INT NULL,
  `totalPedido` DECIMAL(10,2) NULL,
  `desconto` DECIMAL(10,2) NULL,
  `tipoRecebimento` INT NULL,
  `valorRecebido` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_pedidos_funcionarios1_idx` (`idFuncionario` ASC),
  INDEX `fk_pedidos_mesas1_idx` (`idMesa` ASC),
  CONSTRAINT `fk_pedidos_funcionarios1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `sistemagerente`.`funcionarios` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_mesas1`
    FOREIGN KEY (`idMesa`)
    REFERENCES `sistemagerente`.`mesas` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemagerente`.`itensPedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemagerente`.`itensPedidos` (
  `idPedido` INT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `idProduto`),
  INDEX `fk_pedidos_has_produtos_produtos1_idx` (`idProduto` ASC),
  INDEX `fk_pedidos_has_produtos_pedidos1_idx` (`idPedido` ASC),
  CONSTRAINT `fk_pedidos_has_produtos_pedidos1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `sistemagerente`.`pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_produtos_produtos1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `sistemagerente`.`produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
